name: Basic Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: install cowsay
        run: sudo apt-get install -y cowsay

      - name: run the cowsay
        run: cowsay -f dragon "run the cover, I am DRAGON" >> dragon.txt

      - name: list the file 
        run: cat dragon.txt

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass jq

      - name: Say Hello
        run: echo "🚀 Basic GitHub Action is running!"
