name: Basic Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: install cowsay
        run: sudo apt-get install -y cowsay

      - name: run the cowsay
        run: cowsay -f dragon "run the cover, I am DRAGON" >> dragon.txt

      - name: upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-file
          path: dragon.txt

      - name: show artifact file 
        run: |
            pwd
            ls -lart 

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: download the artifact
        uses: actions/download-artifact@v4
        with:
          name: my-file


      - name: show artifact file 
        run: |
            pwd
            ls -lart
            


      - name: list the file 
        run: cat dragon.txt


      - name: Say Hello
        run: echo "🚀 Basic GitHub Action is running!"
