name: Basic Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass jq

      - name: Say Hello
        run: echo "🚀 Basic GitHub Action is running!"
